const ActionTypes = {
    USERNAME: "USERNAME",
    SIGNIN: "SIGNIN",
    SIGNUPERROR: 'SIGNUPERROR',
    SIGNOUT: "SIGNOUT",
    NGODATA: 'NGODATA',
    SIGNINERROR: 'SIGNINERROR',
    REQUIRMENTPOST: 'REQUIRMENTPOST',
    REQUIRMENTPOSTKEYS: 'REQUIRMENTPOSTKEYS',
    USERSDATA: 'USERSDATA',
    ACTIVELIKE: 'ACTIVELIKE',
    COMMENTBOX: 'COMMENTBOX',
    CURRENTUSER: 'CURRENTUSER',
    POSTCOMMENT: 'POSTCOMMENT',
    COMMENTDATA: 'COMMENTDATA',
    DONATIONMONEYINDEX: 'DONATIONMONEYINDEX',
    DONATIONMONEY: 'DONATIONMONEY'
    
}

export default ActionTypes;
