const ActionTypes = {
    CURRENTUSER: 'CURRENTUSER',
    DONATORSDATA: 'DONATORSDATA',
    NGOSDATA: 'NGOSDATA',
    REQUIRMENTPOSTKEYS: 'REQUIRMENTPOSTKEYS',
    REQUIRMENTPOST: 'REQUIRMENTPOST',
    LIKEDATA: 'LIKEDATA',
    COMMENTDATA: 'COMMENTDATA',
    ERRORSN: 'ERRORSN',
    NGOSREQUEST: 'NGOSREQUEST',
    NGOPOSTREQ: 'NGOPOSTREQ',
    NGOPOSTREQKEY : 'NGOPOSTREQKEY'
}

export default ActionTypes;
